# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170612_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'contacts'},
        ),
    ]
