# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='account',
        ),
    ]
