# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dreamreal_uuid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dreamreal',
            table=None,
        ),
    ]
