# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170625_1352'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dreamreal',
            table='dreamreal',
        ),
    ]
